[2025-04-30T04:21:16.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-30T04:21:16.587+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_pipeline_v2.load_data manual__2025-04-30T04:21:03.269686+00:00 [queued]>
[2025-04-30T04:21:16.610+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_pipeline_v2.load_data manual__2025-04-30T04:21:03.269686+00:00 [queued]>
[2025-04-30T04:21:16.612+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-30T04:21:16.640+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-30 04:21:03.269686+00:00
[2025-04-30T04:21:16.652+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=116) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-30T04:21:16.654+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2025-04-30T04:21:16.655+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_csv_pipeline_v2', 'load_data', 'manual__2025-04-30T04:21:03.269686+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmppawtu0xq']
[2025-04-30T04:21:16.656+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask load_data
[2025-04-30T04:21:16.726+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_csv_pipeline_v2.load_data manual__2025-04-30T04:21:03.269686+00:00 [running]> on host 5d323234f92c
[2025-04-30T04:21:16.891+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_csv_pipeline_v2' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T04:21:03.269686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T04:21:03.269686+00:00'
[2025-04-30T04:21:16.894+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-30T04:21:16.895+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-30T04:21:16.896+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2025-04-30 04:21:16.588769+00:00
[2025-04-30T04:21:16.897+0000] {logging_mixin.py:190} INFO - Dag name:etl_csv_pipeline_v2 and current dag run status:running
[2025-04-30T04:21:16.897+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-30T04:21:16.923+0000] {load.py:26} WARNING - ⚠️ El archivo de salida ya existía y fue sobrescrito: data/output/superstore_clean.csv
[2025-04-30T04:21:16.969+0000] {load.py:30} INFO - ✅ Archivo final guardado en data/output/superstore_clean.csv
[2025-04-30T04:21:16.971+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-30T04:21:16.992+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-30T04:21:16.994+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_csv_pipeline_v2, task_id=load_data, run_id=manual__2025-04-30T04:21:03.269686+00:00, execution_date=20250430T042103, start_date=20250430T042116, end_date=20250430T042116
[2025-04-30T04:21:17.057+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-30T04:21:17.059+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-30T04:21:17.060+0000] {logging_mixin.py:190} INFO - Dag name:etl_csv_pipeline_v2 queued_at:2025-04-30 04:21:03.290886+00:00
[2025-04-30T04:21:17.061+0000] {logging_mixin.py:190} INFO - Task hostname:5d323234f92c operator:PythonOperator
[2025-04-30T04:21:17.113+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-30T04:21:17.159+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-30T04:21:17.165+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
